name: beta
# 触发器设置
on:
  push:
    # 任何分支push都触发
    branches:
      - "**"
    # 排除tag push
    tags-ignore:
      - "*"

# 项目任务，任务之间可以并行调度
jobs:
  build:
    # 选择云端运行的环境
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        id: time # 为此步骤设置一个id，以便后续引用其输出
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          # 这里用到了github的secrets功能，避免账户和密码随仓库泄露
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # 开始构建镜像
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/qmediasync:beta
          file: Dockerfile_beta
          platforms: linux/amd64
          build-args: |
            APP_VERSION=${{ github.ref_name }}.${{ steps.time.outputs.date }}
            PUBLISH_DATE=${{ steps.time.outputs.date }}
            FANART_API_KEY=${{ secrets.FANART_API_KEY }}
            DEFAULT_TMDB_ACCESS_TOKEN=${{ secrets.DEFAULT_TMDB_ACCESS_TOKEN }}
            DEFAULT_TMDB_API_KEY=${{ secrets.DEFAULT_TMDB_API_KEY }}
            DEFAULT_SC_API_KEY=${{ secrets.DEFAULT_SC_API_KEY }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.RELEASE_TOKEN }}
